set -g prefix2 C-Space

set -g mouse on
set -g mode-keys vi
set -g renumber-windows on
set -g status-position top
set -s escape-time 0
set -g history-limit 10000
set -g focus-events on
set -sa terminal-features ',*:RGB'
set -g allow-passthrough on

bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -N "popup terminal" C-f display-popup -w 90% -h 90% -E "tmux new-session -A -s scratch"

bind -N "split window up-down" '"' split-window -c "#{pane_current_path}"
bind -N "split window left-right" % split-window -h -c "#{pane_current_path}"
bind -N "create new window" c new-window -c "#{pane_current_path}"

bind -N "reload config" r source-file ~/.tmux.conf \; display "config reloaded"

bind -N "hop pane-fully leftwards" h select-pane -L
bind -N "hop pane-fully downwards" j select-pane -D
bind -N "hop pane-fully upwards" k select-pane -U
bind -N "hop pane-fully rightwards" l select-pane -R

bind -N "pane-ful resize leftwards" -n M-H resize-pane -L 1
bind -N "pane-ful resize downwards" -n M-J resize-pane -D 1
bind -N "pane-ful resize upwards" -n M-K resize-pane -U 1
bind -N "pane-ful resize rightwards" -n M-L resize-pane -R 1

bind -N "choose a widow to pane-alize" C-j choose-tree -Zw "join-pane -s '%%'"
